Remove counter compatibility code from ust comm
Only the ust-ctl (sessiond) side is required to be backward compatible
with older UST. There is already a major protocol version bump (9 -> 10)
planned for 2.14, which will preserve backward compatibility for the
sessiond, but breaks compatibility for UST.

A 2.14 UST does not interact with a 2.13 sessiond. From the sessiond
console:

Error: UST app recv reg unsupported version 10.0. Supporting 9.0

Therefore, we can remove the useless compat code from UST.

Signed-off-by: Mathieu Desnoyers <mathieu.desnoyers@efficios.com>
Change-Id: I63484c635f295871dd8863a412ae93724ba71f12